name: jm${artifactId}
version: ${version}
description: ${description}
load: STARTUP
author: juanmuscaria
website: https://juanmuscaria.github.io
main: io.github.juanmuscaria.core.JMCore
softdepend:
  - ProtocolLib
  - Vault
depend:
  - Yamler